// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwqwukqukudpzgdkyasu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3cXd1a3F1a3VkcHpnZGt5YXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyNzY1NjksImV4cCI6MjA1Mjg1MjU2OX0.RPClMfIEjqv91Rg7lxf6DzeFQnyheMFXOw_taOdOiEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);